eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: roles
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/roles/**
        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**

management:
  tracing:
    sampling:
      probability: 1.0